### PR TITLE
lossen up props.children

### LINKED ISSUE #14: Can we lossen up props.children check?
Currently it will show warning if you provided anything else than text. But in react-native it's [possible](https://facebook.github.io/react-native/docs/text.html#nested-text) to nest text one into another.

My use case is to show [icon](https://github.com/oblador/react-native-vector-icons) next to text 

```javascript
<Button>
    <Icon name="sign-in"/><Text> Sign up </Text>
</Button>
```

### PR DESCRIPTION
**Pull request by gorangajic**
fixes #14

### CODE REVIEW

**Comment by alvaromb** [comment]
Hi @gorangajic and sorry for the delay! :baby_bottle: :baby: 

I would prefer this instead of ``any`` prop type:

```js
// Anything that can be rendered: numbers, strings, elements or an array
// (or fragment) containing these types.
optionalNode: React.PropTypes.node,

// A React element.
optionalElement: React.PropTypes.element,
```

Would that work for you?

**Comment by gorangajic** [comment]
`React.PropTypes.node` works, updated commit

**Comment by charpeni** [comment]
Merge?

**Comment by aminroosta** [comment]
@alvaromb please merge this :-)

**Comment by gorangajic** [comment]
btw I have updated pull request again

**Comment by alvaromb** [comment]
Let's keep this feature on #29

**Pull request closed without merging**
