### PR TITLE
removing react-native dependency

### PR DESCRIPTION
**Pull request by FaridSafi**
when installing this component inside another component, it forces re-install of react-native

### CODE REVIEW

**Comment by alvaromb** [comment]
Hi @FaridSafi!

Removing RN from dependencies is not a good option, but I would accept a PR to change RN from ``dependencies`` to ``peerDependencies``.

**Comment by FaridSafi** [comment]
I confirm the component will still work in a react-native project without the dependency :)
It's the same issue with peerDependencies

**Comment by alvaromb** [comment]
React Native is a dependency because this package will not work unless you use it under a RN environment. Thus, we need to specify somewhere that dependency. Take a look at [this](http://blog.nodejitsu.com/package-dependencies-done-right/) article about npm dependencies.

**Comment by alvaromb** [comment]
Just FYI, I've recently merged this: https://github.com/APSL/react-native-button/pull/7

Expect a release today! :rocket:

**Comment by alvaromb** [comment]
Hi @FaridSafi!

Removing RN from dependencies is now widely accepted due to release candidate versions. I've just published https://github.com/APSL/react-native-button/releases/tag/v2.4.0/

**Pull request closed without merging**
