### PR TITLE
Adds optional disabledStyle prop

### PR DESCRIPTION
**Pull request by danielweinmann**
What do you think of this, @alvaromb? Thanks for the component, BTW!

### CODE REVIEW

**Comment by alvaromb** [comment]
Hey @danielweinmann, the PR looks great!! Will merge tomorrow at the office :)

Many thanks!

**Comment by danielweinmann** [comment]
Thanks! Can you let me know when you publish this to npm, @alvaromb?

I'm contributing to @FaridSafi's https://github.com/FaridSafi/react-native-gifted-form, which uses your package, and want to add capabilities to style the disabled button there as well ;)

**Comment by alvaromb** [comment]
I'm publishing it right now :)

**Comment by alvaromb** [comment]
Just published https://github.com/APSL/react-native-button/releases/tag/v2.4.2 to npm

:rocket: :shipit:

**Comment by FaridSafi** [comment]
Hello, thank you @alvaromb, I will include your new version

**Comment by danielweinmann** [comment]
@FaridSafi I've just sent a PR that depends on 2.4.2 of @alvaromb's package ;)

**Pull request merged**
